/* Right click on customer_behviour and click on query tools */
--COMMA TELL THE NUMBER OF COLUME TO RETURN
select * from customer limit 20;

-- Total revenue generated by male vs female customers
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;

--Which customers nsed a dscount but still spend more than avg purchase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

--Which are the top 5 products with highest average review rating
--Review rating column was double precision column when imported from jupyter so we type cast it to numeric for avg to work
--basically it may be imported as varchar or char so we convert to numeric
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Compare the average purchase amounts between standard and edxpress shipping
select shipping_type,
ROUND(AVG(purchase_amount),2) AS avg_purchase
from customer 
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Do suubscribed customers spend more? 
--Compaure avg spend and total revenue  between subscribers and non subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Which 5 products have the highest percentage of purchases with discount applied
select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Segment customers into new,returning and loyal based on their total number of previous purchases
--and show count of each segment
with customer_type as (
select previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)
select customer_segment, COUNT(*) as "Number of customers"
from customer_type
group by customer_segment;

--What are the top 3 most purchased products within each category
-- rank ,dense rank,row number are types of rankings
-- Top 3 most purchased products within each category
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;


--Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5 
group by subscription_status;

--Revenue contribution of each age group
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;